// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqivftgdihlwrtxmxfie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxaXZmdGdkaWhsd3J0eG14ZmllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDEyMDIsImV4cCI6MjA3NDIxNzIwMn0.cuQ8HXZ4XIIjv4fEkjofEuqZZ8FgsPtsTreR_1eUWV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});